# Generated by Django 3.1.7 on 2021-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('time_to_destroy', models.IntegerField()),
                ('amount_to_read', models.IntegerField(default=10)),
            ],
        ),
    ]
