# Generated by Django 3.1.7 on 2021-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secrtemessage',
            name='author',
        ),
        migrations.AlterField(
            model_name='secrtemessage',
            name='time_to_destroy',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
