# Generated by Django 3.1.7 on 2021-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_message', '0002_auto_20210309_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrtemessage',
            name='amount_to_read',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
